name: XYZ
main: com.ethanpilz.xyz.XYZ
version: 1.2.4
api-version: "1.13"
description: Player location management system
author: Ethan Pilz
commands:
    xyz:
        description: XYZ user commands
    xyzadmin:
        description: XYZ Admin Commands
    xyza:
        description: Alias for XYZAdmin
permissions:
    XYZ.*:
        description: Gives access to all XYZ commands
        children:
            XYZ.admin: true
            XYZ.user: true
            XYZ.homes: true
        default: op
    XYZ.admin:
        description: Gives admin access to XYZ admin commands
        default: op
    XYZ.user:
        description: User level permissions to use XYZ
        default: true
    XYZ.homes:
        description: Gives players already with xyz.user access to sethome and home
        default: false
